#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
}

start() {
	ebegin "Start ${SVCNAME}"

	# warn on low ulimit
	local ulimit=$(ulimit -n)
	if [[ $ulimit < 4096 ]]; then
		ewarn "Current ulimit -n is $ulimit. 4096 is the recommended minimum."
	fi

	start-stop-daemon --background --start --user ${RIAK_USER} \
			--exec ${RIAK_EXEC} -- start
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	local beam=$(pidof ${RIAK_ERTS_PATH}/bin/beam.smp)
	# if riak stop fails use more force
	${RIAK_EXEC} stop 2>&1 > /dev/null || start-stop-daemon \
			--stop --quiet --retry=TERM/30/KILL/5 \
			--user ${RIAK_USER} --exec $beam

	einfo "Stopping epmd"
	local epmd=$(pidof ${RIAK_ERTS_PATH}/bin/epmd)
	[[ $epmd ]] && kill $epmd

	eend $?
}

reload() {
	ebegin "Reloading ${SVCNAME}"
	${RIAK_EXEC} restart
	eend $?
}
